name: Trigger auto deployment for album-ui

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/album-ui-AutoDeployTrigger-3a77cb9c-7744-4f4b-891c-7d645fcf3f5c.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ALBUMUI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/src 
          registryUrl: cab7bb816627acr.azurecr.io
          registryUsername: ${{ secrets.ALBUMUI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ALBUMUI_REGISTRY_PASSWORD }}
          containerAppName: album-ui
          resourceGroup: album-containerapps
          imageToBuild: cab7bb816627acr.azurecr.io/album-ui:${{ github.sha }}
          dockerfilePath: Dockerfile

     

